code --install-extension 2gua.rainbow-brackets
code --install-extension abusaidm.html-snippets
code --install-extension alexiv.vscode-angular2-files
code --install-extension Angular.ng-template
code --install-extension bradgashler.htmltagwrap
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension DSKWRK.vscode-generate-getter-setter
code --install-extension ecmel.vscode-html-css
code --install-extension eg2.tslint
code --install-extension eriklynd.json-tools
code --install-extension esbenp.prettier-vscode
code --install-extension infinity1207.angular2-switcher
code --install-extension jchannon.csharpextensions
code --install-extension johnpapa.Angular2
code --install-extension joshuapoehls.json-escaper
code --install-extension ksubedi.net-core-project-manager
code --install-extension Leopotam.csharpfixformat
code --install-extension minhthai.vscode-todo-parser
code --install-extension ms-mssql.mssql
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.PowerShell
code --install-extension ms-vscode.resharper9-keybindings
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension robertohuertasm.vscode-icons
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker